name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     - name: Run Tests
#       run: ./gradlew test --stacktrace
    - name: Build Assessment Model
      run: ./gradlew :assessmentModel:build
    - name: Upload debug aar
      uses: actions/upload-artifact@v1
      with:
          name: androidAssessmentModel-debug-aar
          path: assessmentModel/build/outputs/aar/assessmentModel-debug.aar
    - name: Upload ios debug framework
      uses: actions/upload-artifact@v1
      with:
          name: iosDebugFramework
          path: assessmentModel/bin/ios/debugFramework/assessmentModel.framework
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: androidAapp-debug
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
